version: "3.2"
services:
  app:
    build: .
    image: awss3operation:latest
    container_name: myapp
    volumes:
      - ./app:/go/src/app
    working_dir: /go/src/app
    tty: true
    ports:
      - 80:80
